# Simulation exercises



In [1]:
# Don't change this cell; just run it.
import numpy as np  # The array library.

# The OKpy testing system.
from client.api.notebook import Notebook
ok = Notebook('simulation.ok')

Assignment: simulation
OK, version v1.18.1



## The crooked Euro

With thanks to [Allen Downey](https://tinyurl.com/inference3), and [David
MacKay](http://www.inference.org.uk/mackay).

Some people were worried that the [Euro coin was asymmetric](https://www.theguardian.com/world/2002/jan/04/euro.eu2).  A quick test, described in that page found that:

> When tossed 250 times, the one euro coin came up heads 139 times and tails
> 111.

For a fair, balanced coin, the chance of a head is 0.5 (50%) on each coin
toss.  Therefore we expect *around* 50% of these 250 coin tosses to be heads -
therefore, we expect *around* 125 heads.

In fact we got 139; that a seems a rather high number.

How often would we expect such a number just by chance, *if it is really true
that the chances of heads on any on toss is 0.5*?

What do we mean by *such a number* above? We are concerned that 139 is rather
high.   We are therefore interested to see whether we get 139 again.  But we
know that getting *exactly* 139 is going to be unlikely, even if the coin is
biased; even *exactly 125* is unlikely if the coin is fair.  And, if the coin
is fair, and 139 is surprising, we would be even more surprised by 140, 141
and so on.  So our interest is to see how often a fair coin will give us a
number of heads of 139, or even a greater number.

[this logic is important -- we want to know how unlikely 139 is, or _any other
result that is even more unlikely than 139_.  Why do we do it this way?  
Getting some number **exactly** (i.e. 139), as explained above, is even harder than getting some
number that is at least as big as 139 (but could also be bigger).  
We don't really care about the exact value. We just want to know if numbers that are _as big as 139 or bigger_ are unusual if we flip a fair coin. Hitting exactly 139 is hard (think of the lottery).  
Hitting a number that is 139 or bigger is less hard. 

You could also think about it this way.  The coin would not be unfair
if we got 139 heads, but then fair again if we got 140.]

We therefore want to check how often we get *139 or more* heads in 250 coin tosses, if the coin is fair.

Call one *trial* - the result of 250 coin tosses.

For simulations like these, it is very often useful to first build a cell with one trial, to work out the logic of a single trial, and only then put that logic inside the for loop, to do multiple trials.

To help you, here is the logic for one trial:

In [2]:
# One trial of the coin-tossing problem.
# Toss 250 coins, each with a 50% chance of giving heads (1).
tosses = np.random.randint(0, 2, size=250)
# Count the number of heads.
n_heads = np.sum(tosses)

Remember, our job in the *for loop* is first: do the single trial logic above
and second;  store the result to analyze later. Here the result of the single
trial is `n_heads`.

In [3]:
# Array to store the number of heads on each trial.
counts = np.zeros(10000)
for i in np.arange(10000):
    # Each indented statement gets run on every trial
    tosses = np.random.randint(0, 2, size=250)
    n_heads = np.sum(tosses) # there is more than one way to do this - np.count_nonzero(tosses) works also
    counts[i] = n_heads
p_crooked = np.count_nonzero(counts >= 139 ) / 10000
p_crooked

0.0429

In [4]:
_ = ok.grade('q_p_crooked')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed



## Penalty shootout technique

Jen is the penalty taker for her football team.

She's been doing this for a long time.  She thinks she normally has a 80%
chance of scoring.

In the last 15 penalties she has taken, she has been trying a new technique.
She scored on all 15 penalties.

How certain can she be that this would not have happened, using the old
technique?

As usual, we first consider the logic for a single trial.  A single trial is
15 of Jen's penalty shots.  The result of the trial is the number of penalty
shots that went in.  For each shot, there is a 80% chance of it going in.
Careful, this is different from the case of the coin toss, where each coin
toss had a 50% chance of being heads.

Hint: one good option is `np.random.randint`.  Read the help with
`np.random.randint?` in a new cell.  Consider the logic in the [reply to the
Supreme Court](https://uob-ds.github.io/cfd2021/iteration/reply_supreme).

Try filling in the cell below to get the logic for one trial.  Run the cell a
few times to see whether you are getting a plausible number of scores.

In [5]:
#- One trial is 15 penalty shots, each with 80% chance of scoring.
shots = np.random.randint(0, 10, 15)
scores = np.count_nonzero(shots  > 1)
# Scores should be some number between 0 and 15, with higher values being much
# more likely than lower values (because of the 80% chance of scoring).
scores

12

Now you should have the logic for one trial, you can put it into the for loop.  Remember to store the result of each trial, within the for loop.

In [6]:
#- Calculate the probability of Jen scoring 15 out of 15 penalties.
counts = np.zeros(10000)
for i in np.arange(10000):
    # Each indented statement gets run on every trial
    shots = np.random.randint(0, 10, 15)
    scores = np.count_nonzero(shots > 1)
    counts[i] = scores
p_15_of_15 = np.count_nonzero(counts == 15) / 10000
p_15_of_15

0.0346

In [7]:
_ = ok.grade('q_1_penalties')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed



## Aim big

John is playing Monopoly.  His piece, the top hat, is sitting in a really bad
spot, just in front of some expensive hotels.  He is about to roll the two
6-sided die.  He needs a score of 10 or more to skip over the hotels.  What
are John's chances?

Solve by simulation.

Hint: consider `np.random.randint` again.

Here is a template for the logic of one trial.  The result you see for `score`
should be the result of rolling two six-sided dice, and adding the scores.  As
usual, we expect numbers like 7 or 6 to be a lot more common than scores like
2 or 12, because there are six combinations of the two dice scores that add up
to 7 (1 + 6, 2 + 7 ...) and only one combination that adds up to 12.

In [8]:
dice = np.random.randint(1, 7, 2) # notice -- start at 1, finish before 7
score = np.sum(dice)
# The addition of the two dice. This should result in numbers like 7 or 6
# more often than numbers like 2 or 12.
score

9

Now put this single-trial logic in the for loop.  Don't forget to store the
result of the trial, within the loop.

In [9]:
#- Calculate the probability of getting 10 or more with two dice.
counts = np.zeros(10000)
for i in np.arange(10000):
    dice = np.random.randint(1, 7, 2)
    score = np.sum(dice)
    counts[i] = score
p_10_or_more = np.count_nonzero(counts >= 10) / 10000
p_10_or_more

0.1605

In [10]:
_ = ok.grade('q_2_monopoly')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed



## Blackjack

Given any three random playing cards, what is the chance that the ranks of the
three cards add up to 21?

10, jack, queen and king all count as 10.  For example, one way of getting 21
is a seven, a four and a king.


### Simple version

Assume the three cards are each dealt from the top of a full shuffled deck.
Therefore, the procedure is:

* you shuffle, look at the top card, record the rank, you put it back.
* repeat twice more.

Assume that the ace counts as 1.  What are the chances of getting
a total rank of 21?

Hint: look at the array `card_deck` in the code cell below.

Investigate `np.random.choice` to use this array for the problem.

Consider whether you want to draw cards with replacement, or without
replacement.

In [11]:
# First - define the ranks of all the cards in one suit.
# Ace is 1; Jack, Queen, King are all 10.
ranks = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10])
# Next - make a deck of cards by replicating ranks four times.
# The line below repeats each element four times.
card_deck = np.repeat(ranks, 4)
card_deck

array([ 1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  5,
        5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
        9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10])

Here is a cell for you to work on the logic for a single trial:

In [12]:
#- "cards" should be an array with 3 elements, each of which comes from the
#- "card_deck" array.
cards = np.random.choice(card_deck,3,replace=False)
#- "rank_total" should be the result of adding up the ranks in the cards.
rank_total = np.sum(cards)
# The result should be some number between 3 and 30 ... (why?).
rank_total

28

In [13]:
# Ranks of all the cards in one suit.
ranks = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10])
card_deck = np.repeat(ranks, 4)
num_repeats = 10000
rank_total = np.zeros(num_repeats)
for i in np.arange(0,num_repeats):
    cards = np.random.choice(card_deck,3,replace=False)
    rank_total[i] = np.sum(cards)
p_total_21 = np.count_nonzero(rank_total == 21)/num_repeats
p_total_21

0.0781

In [14]:
_ = ok.grade('q_3_simple_blackjack')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed



## Less simple version

Assume the cards are drawn as they were for the problem above.

Now the ace can count as 1 or as 11, whichever gives a total of 21.  To make things a bit simpler, the two options are:

* all aces in a hand count as 1, OR
* all aces in a hand count as 11.

Your job is to choose the option from the list above, that gives you 21, if that is possible.

For example, if you have a hand (Ace, Ace, 9), then your two options are ranks
(1, 1, 9) (for a total of 21) or (11, 11, 9) (for a total of 31), in which
case you would choose the ace = 1 rank.  On the other hand, you might have
(Ace, 2, 8) in which case you would chose the ace = 11 rank.  In this
simplified case (Ace, Ace, 8) can only give 10 (for ace=1) or 30 (for ace=11).

In this situation, what are the chances of a total rank of 21?

The hints below are for one way of solving this case.   There are other ways of solving this case; feel free to chose the method you prefer.

*Hint 1*: you can change values of 1 to 11 like this:

In [15]:
# Make an example array
some_cards = np.array([1, 3, 5, 1, 2])
some_cards

array([1, 3, 5, 1, 2])

In [16]:
# Make a Boolean array that has True for positions where some_cards == 1
card_eq_1 = some_cards == 1
card_eq_1

array([ True, False, False,  True, False])

In [17]:
# In the found positions, change the value to 11
some_cards[card_eq_1] = 11
some_cards

array([11,  3,  5, 11,  2])

*Hint 2*: You might want to use this kind of trick more than once in your
solution.

*Hint 3*: You might consider having two arrays of results for each hand, one for the case where aces count as 1 and the other for case where aces count as 11, like this:

In [18]:
# Initialize result arrays.
rank_totals_1 = np.zeros(10000)
rank_totals_11 = np.zeros(10000)

Here is the cell for your solution:

In [19]:
# I think this is the way intended by the hints above -- 
# below see another way that might feel more like what you'd do as a player

ranks = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10])
card_deck = np.repeat(ranks, 4)
num_repeats = 10000
rank_totals_1 = np.zeros(num_repeats)
rank_totals_11 = np.zeros(num_repeats)
for i in np.arange(0,num_repeats):
    cards = np.random.choice(card_deck,3,replace=False)
    rank_totals_1[i] = np.sum(cards)
#    print(cards," = ",rank_totals_1) # check 'cards' values and sum - don't use with 10000 repeats
    cards[cards == 1] = 11 # change any ones to 11
    rank_totals_11[i] = np.sum(cards)
#    print(cards," = ",rank_totals_11)   # check that this is working - don't use with 10000 repeats

rank_totals_11[rank_totals_1 == 21] = 0  # can't count a result twice - 
# this would happen if no cards are 1, but the total is 21

p_flex_total_21 = (np.count_nonzero(rank_totals_1 == 21) + np.count_nonzero(rank_totals_11 == 21)) / num_repeats
p_flex_total_21

0.0902

In [20]:
np.count_nonzero(rank_totals_11 == 21)

80

In [21]:
np.count_nonzero(rank_totals_1 == 21)

822

In [22]:
# another way
ranks = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10])
card_deck = np.repeat(ranks, 4)
num_repeats = 10000
rank_totals = np.zeros(num_repeats)
for i in np.arange(0,num_repeats):
    cards = np.random.choice(card_deck,3,replace=False)
    rank_totals[i] = np.sum(cards)
    if(np.count_nonzero(cards == 1) > 0): # if there are some ones
        if(rank_totals[i] != 21): # only check the other value if we didn't get 21 with 1s
            cards[cards == 1] = 11
            rank_totals[i] = np.sum(cards)

p_flex_total_21 = np.count_nonzero(rank_totals == 21) / num_repeats
p_flex_total_21

0.0894

In [25]:
ranks = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10])
card_deck = np.repeat(ranks, 4)
number_of_hands = 10000
rank_score = np.zeros(number_of_hands) # just use one rank score array
for i in np.arange(0,number_of_hands):
    one_hand_with_1 = np.random.choice(card_deck,3,replace=True)
    rank_score[i] = np.sum(one_hand_with_1)

    if(rank_score[i] != 21): # if we didn't already get 21
        cards_eq_1 = one_hand_with_1 == 1
        one_hand_with_11 = one_hand_with_1 # first make a copy
        one_hand_with_11[cards_eq_1] = 11
        rank_score[i] = np.sum(one_hand_with_11)

    
p_flex_total_21 = (np.count_nonzero(rank_score == 21) / 10000) 
p_flex_total_21

0.0944

In [26]:
_ = ok.grade('q_4_flexi_blackjack')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed



You may have found that allowing aces to count as 11 didn't greatly improve your chances of getting 21.  Why is that?

## Done.

Congratulations, you're done with the assignment!  Be sure to:

- **run all the tests** (the next cell has a shortcut for that),
- **Save and Checkpoint** from the `File` menu,

In [24]:
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=638e377a-b64e-4e49-acd3-821ff6331d40' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>