# More arrays


## About this exercise

This exercise is an edited version of a homework from [the Berkeley data
science course](https://github.com/data-8/data8assets) with thanks.  If you
make a new version of this original, please note that this exercise has a
[CC-BY-NC license](http://creativecommons.org/licenses/by-nc/4.0/); remember to
give attribution to the original authors from the repository above.


## Getting started

Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell to load the provided tests. Each time you start your server, you will need to execute this cell again to load the tests.

In [ ]:
# Don't change this cell; just run it.
import numpy as np  # The array library.
import pandas as pd  # A library for working with data tables.

# The OKpy testing system.
from client.api.notebook import Notebook
ok = Notebook('more_arrays.ok')

Assignment: Homework 2: Arrays and Tables
OK, version v1.18.1



**Important**: The `ok` tests don't always tell you that your answer is
correct. More often, they help catch careless mistakes. It's up to you to
ensure that your answer is correct. If you're not sure, ask someone (not for
the answer, but for some guidance about your approach).

**Important as well**: Don't forget the rules on working together.  See the
class pages for detail.

Once you're finished, select "Save and Checkpoint" in the File menu.


## Experiments, checks

You will often benefit from making extra cells in your notebook to check what
the current variables hold and to experiment with code.  You can insert cells
with the +code button in deepnote, but please consider learning the shortcuts.
Cntl-J or command-J (mac) should add a code cell below the current cell and Cntl-K or command-K should add a code cell above the current cell.

When you do make extra cells, please don't forget to check the notebook again
when you have finished, by saving your work (see below), and running "Restart
and Run All" from the "Kernel" menu.  Make sure you don't get any errors when
you do this.  If necessary, edit or delete any experimentation cells.  We run
this check when marking your notebook, and we will subtract marks if we have to
fix errors in order to run the notebook through to the end.


## Creating Arrays

**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. -2
2. the sine of 1.2
3. 3
4. 5 to the power of the cosine of 1.2

*Hint:* `sin` and `cos` are functions in the `np` module.

In [ ]:
weird_numbers = np.array([-2, np.sin(1.2),3,5**np.cos(1.2)])
weird_numbers

array([-2.        ,  0.93203909,  3.        ,  1.79174913])

In [ ]:
_ = ok.grade('q2_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** Make an array called `book_title_words` containing the following three strings: "Eats", "Shoots", and "and Leaves".

In [ ]:
book_title_words = np.array(["Eats", "Shoots", "and Leaves"])
book_title_words

array(['Eats', 'Shoots', 'and Leaves'], dtype='<U10')

In [ ]:
_ = ok.grade('q2_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



Strings have a method called `join`.  `join` takes one argument, an array of
strings.  It returns a single string.  Specifically, the value of
`a_string.join(an_array)` is a single string that's the
[concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting
together") of all the strings in `an_array`, **except** `a_string` is inserted
in between each string

For example, look at this result of doing `join` on `book_title_words` with the
join string `foo`':

In [ ]:
"foo".join(book_title_words)

'EatsfooShootsfooand Leaves'

**Question 3.** Use the array `book_title_words` and the method `join` to make two strings:

1. "Eats Shoots and Leaves" (call this one `without_commas`)
2. "Eats, Shoots, and Leaves" (call this one `with_commas`)

In [ ]:
without_commas = " ".join(book_title_words)
with_commas = ", ".join(book_title_words)  # notice the string is comma plus space
# These lines are just to print out your answers.
print(without_commas)
print(with_commas)

Eats Shoots and Leaves
Eats, Shoots, and Leaves


In [ ]:
_ = ok.grade('q2_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



## 3. Indexing Arrays

These exercises give you practice accessing individual elements of arrays.  In
Python (and in many programming languages), elements are accessed by *index*,
so the first element is the element at index 0.

**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

In [ ]:
some_numbers = np.array([-1, -3, -6, -10, -15])

third_element = some_numbers[2]
third_element

-6

In [ ]:
_ = ok.grade('q3_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** The next cell creates a table that displays some information
about the elements of `some_numbers` and their order.  Run the cell to see the
partially-completed table, then fill in the missing information in the cell
(the strings that are currently "???") to complete the table.

Don't worry about the code to create the "DataFrame"; we will cover that
later.

In [ ]:
#- Replace in ??? placeholders in the next lines.
names = np.array(["first", "second", "third", "fourth", "fifth"])
index = np.array(["0", "1", "2", "3", "4"])
# Don't worry about this code below.
elements_of_some_numbers = pd.DataFrame()
elements_of_some_numbers['English name for position'] = names
elements_of_some_numbers['Index'] = index
elements_of_some_numbers['Element'] = some_numbers
elements_of_some_numbers

,English name for position,Index,Element
0,first,0,-1
1,second,1,-3
2,third,2,-6
3,fourth,3,-10
4,fifth,4,-15


In [ ]:
_ = ok.grade('q3_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 3.** You'll sometimes want to find the *last* element of an array.
Suppose an array has 142 elements.  What is the index of its last element?

In [ ]:
index_of_last_element = 141

In [ ]:
_ = ok.grade('q3_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



More often, you don't know the number of elements in an array, its *length*.
(For example, it might be a large dataset you found on the Internet.)  The
function `len` takes a single argument, an array, and returns the `len`gth of
that array (an integer).

**Question 4.** The cell below loads an array called `president_birth_years`.
The last element in that array is the most recent birth year of any deceased
president. Assign that year to `most_recent_birth_year`.  Again, don't worry
about the code to read the data.

In [ ]:
# Read the presidents data from a data file.
presidents_df = pd.read_csv("president_births.csv")
# Get the birth years column as an array.
president_birth_years = np.array(presidents_df['Birth Year'])

most_recent_birth_year = president_birth_years[-1]  # or else

array_len = len(president_birth_years)
most_recent_birth_year=president_birth_years[array_len-1]
most_recent_birth_year

1917

In [ ]:
_ = ok.grade('q3_4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



## 4. Basic Array Arithmetic


**Question 1.** Multiply the numbers 42, 4224, 424224, and -250 by 157.  For this question, **don't** use arrays.

In [ ]:
first_product = 42*157
second_product = 4224*157
third_product = 424224*157
fourth_product = -250*157
print(first_product, second_product, third_product, fourth_product)

6594 663168 66603168 -39250


In [ ]:
_ = ok.grade('q4_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** Now, do the same calculation, but using an array called
`numbers` and only a single multiplication (`*`) operator.  Store the 4
results in an array named `products`.

In [ ]:
numbers = np.array([42,4224,424224,-250])
products = numbers * 157
products

array([    6594,   663168, 66603168,   -39250])

In [ ]:
_ = ok.grade('q4_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply
each number by 1577.  Compute the fixed products in the cell below using array
arithmetic.  Notice that your job is really easy if you previously defined an
array containing the 4 numbers.

In [ ]:
fixed_products = numbers * 1577
fixed_products

array([    66234,   6661248, 669001248,   -394250])

In [ ]:
_ = ok.grade('q4_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 4.** We've loaded an array of temperatures in the next cell.  Each
number is the highest temperature observed on a day at a climate observation
station, mostly from the US.  Since they're from the US government agency
[NOAA](noaa.gov), all the temperatures are in Fahrenheit.  Convert them all to
Celsius by first subtracting 32 from them, then multiplying the results by
$\frac{5}{9}$. Round each result to the nearest integer using the `np.round`
function.

In [ ]:
#- Don't worry about this code to read the data.
max_temperatures = np.array(pd.read_csv("temperatures.csv")["Daily Max Temperature"])
celsius_max_temperatures = np.round((max_temperatures - 32) * (5/9))
celsius_max_temperatures

array([-4., 31., 32., ..., 17., 23., 16.])

In [ ]:
_ = ok.grade('q4_4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 4
    Failed: 0
[ooooooooook] 100.0% passed



**Question 5.** The cell below loads all the *lowest* temperatures from each
day (in Fahrenheit).  Compute the size of the daily temperature range for each
day.  That is, compute the difference between each daily maximum temperature
and the corresponding daily minimum temperature.

**Give your answer in Celsius!**.

You should round your minimum celsius values *before* subtracting.

In [ ]:
#- Read in the data array for min temperatures
min_temperatures = np.array(pd.read_csv("temperatures.csv")["Daily Min Temperature"])
celsius_min_temperatures = np.round((min_temperatures - 32) * (5/9))

celsius_temperature_ranges = celsius_max_temperatures - celsius_min_temperatures
celsius_temperature_ranges

array([ 7., 10., 13., ..., 18., 12., 11.])

In [ ]:
min_temperatures

array([13, 69, 67, ..., 31, 52, 41])

In [ ]:
_ = ok.grade('q4_5')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



## 5. Old Faithful

Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes
(according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People
are [often told that the geyser erupts every
hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting
time between eruptions is more variable. Let's take a look.

**Question 1.** The first line below assigns `waiting_times` to an array of 272
consecutive waiting times between eruptions, taken from a classic 1938
dataset. Assign the names `shortest`, `longest`, and `average` so that the
`print` statement is correct.

*Hint*: check the various array functions in the [Arrays page of the
textbook](https://uob-ds.github.io/cfd2021/data-types/Arrays).

In [ ]:
# Load the data into an array.
waiting_times = np.array(pd.read_csv('old_faithful.csv')['waiting'])
shortest = np.min(waiting_times)
longest = np.max(waiting_times)
average = np.mean(waiting_times)
print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70.8970588235294 minutes on average.


In [ ]:
_ = ok.grade('q5_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** Assign `biggest_decrease` to the biggest decrease in waiting
time between two consecutive eruptions. For example, the third eruption
occurred after 74 minutes and the fourth after 62 minutes, so the decrease in
waiting time was 74 - 62 = 12 minutes.

*Hint*: check the various array functions in the [Arrays page of the
textbook](https://uob-ds.github.io/cfd2021/data-types/Arrays).

*Hint*: think about how to distinguish an increase from a decrease.

In [ ]:
# let's make a little test array to see what np.diff does before we use it
testtimes = np.array([50,40,30,40])
# notice that testtimes has a decrease, another decrease and then and increase
testdiff = np.diff(testtimes)
print(testdiff)

[-10 -10  10]


In [ ]:
# ok - so a decrease is a negative number, 
# so the biggest decrease will be the smallest negative number - i.e. np.min will find it, 
# but then you need to take away the sign (with * -1 or with abs())
# or you could select the negative numbers, take the absolute value and then take the max
# or you could multiply all numbers by -1 (making decreases positive) and then take the max

differences = np.diff(waiting_times) # a decrease would look like 50, 40 so if diff produces 40-50 then 
biggest_decrease = abs(np.min(differences))  # abs gets rid of the negative, so we just have the size of the difference
biggest_decrease

45

In [ ]:
_ = ok.grade('q5_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 2
    Failed: 0
[ooooooooook] 100.0% passed



**Question 3.** If you expected Old Faithful to erupt every hour, you would
expect to wait a total of `60 * k` minutes to see `k` eruptions. Set
`difference_from_expected` to an array with 272 elements, where the element at
index `i` is the absolute difference between the expected and actual total
amount of waiting time to see the first `i+1` eruptions.

For example, since the first three waiting times are 79, 54, and 74, the total
waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time
for 3 eruptions is 60 * 3 = 180. Therefore, `difference_from_expected.item(2)`
should be $|207 - 180| = 27$.  Notice that that bars either side of the numbers
in $|207 - 180|$ mean the *absolute difference* of that subtraction, so this is also true: $|180 - 207| = 27$.

*Hint* - you may well want to compare a cumulative sum to a range.

*Hint* - first make an array `expected` that has the expected waiting times.

*Hint* - think about what the first value in `expected` will be.

*Hint* - check the [array function page](https://uob-ds.github.io/cfd2021/data-types/Arrays)
again for useful functions to help calculate the cumulative sum.

In [ ]:
expected = np.arange(1,273)
expected = expected * 60
cum_waits = np.cumsum(waiting_times)
difference_from_expected = abs(cum_waits - expected)
difference_from_expected

array([  19,   13,   27,   29,   54,   49,   77,  102,   93,  118,  112,
        136,  154,  141,  164,  156,  158,  182,  174,  193,  184,  171,
        189,  198,  212,  235,  230,  246,  264,  283,  296,  313,  319,
        339,  353,  345,  333,  353,  352,  382,  402,  400,  424,  422,
        435,  458,  462,  455,  477,  476,  491,  521,  515,  535,  529,
        552,  563,  567,  584,  605,  604,  628,  616,  638,  638,  670,
        688,  706,  711,  724,  746,  742,  761,  772,  774,  790,  790,
        808,  824,  847,  862,  884,  894,  899,  912,  940,  956,  976,
        964,  990,  990, 1020, 1010, 1028, 1031, 1043, 1067, 1082, 1073,
       1095, 1097, 1125, 1114, 1137, 1158, 1145, 1169, 1161, 1187, 1208,
       1223, 1222, 1251, 1270, 1269, 1290, 1280, 1305, 1304, 1331, 1324,
       1333, 1350, 1346, 1374, 1395, 1380, 1402, 1397, 1427, 1412, 1435,
       1431, 1460, 1446, 1468, 1459, 1485, 1478, 1497, 1518, 1518, 1540,
       1557, 1573, 1572, 1592, 1581, 1617, 1610, 16

In [ ]:
_ = ok.grade('q5_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 4.** If instead you guess that each waiting time will be the same as
the previous waiting time, how many minutes would your guess differ from the
actual time, averaging over every wait time except the first one.

For example, say the first waiting time was 79 minutes.  That becomes your
guess for the current (second) waiting time.  The current waiting time turns
out to be 54 minutes.  Your guess is out by $|79 - 54| = 25$ minutes. Remember
that the vertical bars in $|79 - 54|$ mean the *absolute difference* of the
subtraction. Your guess for the next waiting time is now 54 minutes.  Say the
actual wait is 74 minutes. This time your guess is out by $|54 - 74| = 20$
minutes.  The average number of minutes you were out, across your two guesses,
is $\frac{25 + 20}{2} = 22.5$ minutes.

One approach is to see that we have to line up the positions 0-almost end with the positions 1-end.  E.g. 

    `real times: 50,70,55,80`
    `   guesses: xx,50,70,55 (can't use 80 as a guess because we don't have a real value to guess for 80)`

Then we start our guesses at position 0 and shift the real times over so the first real
time that we'll guess is in position 1, not position 0.  Arrays need to be:

    ` positions:  0, 1, 2
    `real times: 70,55,80
    `   guesses: 50,70,55

However - this also suggests another approach (that some of you used) that is more compact 

If your guess for 70 is going to be 50 you'll be out by the difference between 70 and 50, then by the difference between 55 and 70, etc.  which is the same thing as 

    ` np.diff(real_times)

In [ ]:
num_waiting_times=len(waiting_times)
waiting_times_to_compare = waiting_times[1:]
# can't have a guess for the first time because none have happened yet,
# so the values to predict start from the second value (index = 1)
# We are predicting the second value through to the last value

guess = waiting_times[0:-1] 
# Our first guess is the first value, which is our guess for the second value.
# Our guess for the last time is the second to last time, 
# so we don't need the last time in the guess array



error = abs(waiting_times_to_compare-guess)

# or else

error1 = abs(np.diff(waiting_times))

average_error = np.mean(error)
# or else
average_error1 = np.mean(error1)
print("Our two methods should give the same answer: 1 = ",average_error," 2 = ",average_error1)

Our two methods should give the same answer: 1 =  20.52029520295203  2 =  20.52029520295203


In [ ]:
_ = ok.grade('q5_4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



## And finally

- **run all the tests** (the next cell has a shortcut for that),
- **Save and Checkpoint** from the `File` menu,

In [ ]:
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 2
    Failed: 0
[ooooooooook] 100.0% passed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 4
    Failed: 0
[ooooooooook] 100.0% passed

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=1d814719-8121-4086-8689-e3d931dfa2cb' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>